cd $AMANITHDIR
make clean
rm $AMANITHDIR/Makefile
rm $AMANITHDIR/3rdpart/Makefile
rm $AMANITHDIR/3rdpart/freetype2/Makefile
rm $AMANITHDIR/3rdpart/libjpeg/Makefile
rm $AMANITHDIR/3rdpart/libpng/Makefile
rm $AMANITHDIR/3rdpart/zlib/Makefile
rm $AMANITHDIR/build/Makefile
rm $AMANITHDIR/examples/Makefile
rm $AMANITHDIR/examples/opengl/Makefile
rm $AMANITHDIR/examples/opengl/animcolor/Makefile
rm $AMANITHDIR/examples/opengl/animshape2d/Makefile
rm $AMANITHDIR/examples/opengl/bezier2d/Makefile
rm $AMANITHDIR/examples/opengl/bspline2d/Makefile
rm $AMANITHDIR/examples/opengl/delaunay2d/Makefile
rm $AMANITHDIR/examples/opengl/font2d/Makefile
rm $AMANITHDIR/examples/opengl/hermite2d/Makefile
rm $AMANITHDIR/examples/opengl/path2d/Makefile
rm $AMANITHDIR/examples/opengl/polyline2d/Makefile
rm $AMANITHDIR/examples/opengl/testglext/Makefile
rm $AMANITHDIR/examples/opengl/testshaders/Makefile
rm $AMANITHDIR/examples/opengl/tesselator2d/Makefile
rm $AMANITHDIR/examples/opengl/vectorizer/Makefile
rm $AMANITHDIR/examples/others/Makefile
rm $AMANITHDIR/examples/others/lowlevel_stuff/Makefile
rm $AMANITHDIR/examples/viewimage/Makefile
rm $AMANITHDIR/plugins/Makefile
rm $AMANITHDIR/plugins/fonts/Makefile
rm $AMANITHDIR/plugins/jpeg/Makefile
rm $AMANITHDIR/plugins/png/Makefile
rm $AMANITHDIR/tools/Makefile
rm $AMANITHDIR/tools/plugwizard/Makefile
rm $AMANITHDIR/tools/uuid_gen/Makefile

rm $AMANITHDIR/lib/*
rm $AMANITHDIR/plugins/lib*

rm $AMANITHDIR/examples/opengl/animcolor/drawanim
rm $AMANITHDIR/examples/opengl/animshape2d/drawanim
rm $AMANITHDIR/examples/opengl/bezier2d/drawbezier
rm $AMANITHDIR/examples/opengl/bspline2d/drawbspline
rm $AMANITHDIR/examples/opengl/delaunay2d/delaunay2d
rm $AMANITHDIR/examples/opengl/font2d/drawfont
rm $AMANITHDIR/examples/opengl/hermite2d/drawhermite
rm $AMANITHDIR/examples/opengl/path2d/path2d
rm $AMANITHDIR/examples/opengl/polyline2d/drawpolyline
rm $AMANITHDIR/examples/opengl/testglext/testglext
rm $AMANITHDIR/examples/opengl/testshaders/testshaders
rm $AMANITHDIR/examples/opengl/tesselator2d/tesselator2d
rm $AMANITHDIR/examples/opengl/vectorizer/vectorizer
rm $AMANITHDIR/examples/others/lowlevel_stuff/lowlevel
rm $AMANITHDIR/examples/viewimage/viewimage
rm $AMANITHDIR/tools/plugwizard/plugwizard
rm $AMANITHDIR/tools/uuid_gen/uuid_gen

make distclean
